# Generated by Django 3.2.3 on 2021-06-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0003_auto_20210619_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='to_do_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
