# Generated by Django 3.2.3 on 2021-05-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Model_hardware',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='model',
            new_name='model_hardware',
        ),
    ]
