# Generated by Django 3.2.3 on 2021-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinelog',
            name='notes',
            field=models.TextField(max_length=2096),
        ),
    ]
