# Generated by Django 3.2.3 on 2021-07-05 11:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_alter_routinelog_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservicecontact',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='asset_type',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='assetcase',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='assetcase',
            name='user_report_it',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='bundle_reservation',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='externalserviceposition',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='loan_asset',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='locations',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='model_hardware',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='one2oneinfo',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='one2oneinfolog',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='routinelog',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='routines',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
