# Generated by Django 3.2.3 on 2021-05-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_auto_20210521_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='model_hardware',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='room_type',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='loan_asset',
            name='loaner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_app.loaner_type'),
        ),
        migrations.AddField(
            model_name='loan_asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_app.locations'),
        ),
        migrations.AlterField(
            model_name='bundle_reservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_app.locations'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_app.locations'),
        ),
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=448, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_app.room_type'),
        ),
    ]
