# Generated by Django 3.2.3 on 2021-05-25 15:12

import UnordToolsProject.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=UnordToolsProject.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
