# Generated by Django 3.2.3 on 2021-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_asset_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_loaned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
