# Generated by Django 3.2.3 on 2021-09-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0005_asset_is_loaned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_asset',
            name='loaner_address',
        ),
    ]
