# Generated by Django 3.2.3 on 2021-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0005_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_hardware',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
