# Generated by Django 3.2.3 on 2021-09-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0006_remove_loan_asset_loaner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_asset',
            name='eduName',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='loan_asset',
            name='endEduDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
