# Generated by Django 3.2.3 on 2021-09-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0008_sms_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_asset',
            name='sms_automatic',
            field=models.BooleanField(default=False),
        ),
    ]
