# Generated by Django 3.2.3 on 2021-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0008_one2oneinfo_one2oneinfolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one2oneinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
