# Generated by Django 3.2.3 on 2021-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0009_loan_asset_sms_automatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_asset',
            name='dropped_out_of_school',
            field=models.BooleanField(default=False),
        ),
    ]
