# Generated by Django 3.2.3 on 2021-06-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0010_auto_20210617_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalservice',
            old_name='company_support_telefon',
            new_name='company_support_telephone',
        ),
        migrations.RenameField(
            model_name='externalservice',
            old_name='company_telefon',
            new_name='company_telephone',
        ),
        migrations.RemoveField(
            model_name='assetlog',
            name='date_time_log',
        ),
        migrations.AddField(
            model_name='severitylevel',
            name='sl_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetcase',
            name='notes',
            field=models.TextField(blank=True, max_length=448, null=True),
        ),
        migrations.AlterField(
            model_name='assetcase',
            name='solved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetcase',
            name='user_quicklink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetcase',
            name='zendesk_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
