# Generated by Django 3.2.3 on 2022-11-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0010_loan_asset_dropped_out_of_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_asset',
            name='responsible_teacher_initials',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='loan_asset',
            name='responsible_teacher_received_mail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
